name: Godot Export and Upload to Itch

on: [push, pull_request]

env:
  GODOT_VERSION: "4.6"
  GODOT_STATUS: "stable"
jobs:
  import-assets:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.6
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Cache import assets
        uses: actions/cache@v3
        with:
          path: .godot/imported/
          key: import-assets-${{ runner.os }}-${{ github.sha }}
      - name: Import assets
        run: godot --headless --verbose --editor --quit

  export-game:
    runs-on: ubuntu-latest
    needs: import-assets
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: .godot/imported/
          key: import-assets-${{ runner.os }}-${{ github.sha }}
      - name: Export Game using Godot
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: "https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-${{ env.GODOT_STATUS }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_STATUS }}_linux.x86_64.zip"
          godot_export_templates_download_url: "https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-${{ env.GODOT_STATUS }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_STATUS }}_export_templates.tpz"
          archive_output: true
          presets_to_export: Web
          cache: false
      - name: Upload HTML5
        uses: actions/upload-artifact@v4
        with:
          name: HTML5
          path: /home/runner/.local/share/godot/archives/Web.zip

  deploy-to-itchio-web:
    runs-on: ubuntu-latest
    needs: export-game
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/download-artifact@v4
        with:
          name: HTML5
      - name: Deploy to Itch.io (HTML5)
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
          PACKAGE: Web.zip
